from pathlib import Path


HARNESS_LOGIC_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = HARNESS_LOGIC_DIR.parent
DEFAULT_HARNESS_ROOT = HARNESS_LOGIC_DIR / "data"
DEFAULT_HARNESS_MODEL_ROOT = PROJECT_ROOT / "models"
DEFAULT_CHARACTER_SYSTEM_ROOT = PROJECT_ROOT / "character_system"
DEFAULT_CHARACTER_EVIDENCE_ROOT = PROJECT_ROOT / "data" / "novel_test"
DEFAULT_PREDICT_LENGTH = 1024
MODEL_SUBDIR = "models"
MIN_IMAGE_SLICE = 1
MAX_IMAGE_SLICE = 9
DEFAULT_IMAGE_SLICE = MAX_IMAGE_SLICE
